---

 - name: Install container-selinux if required      --    --   --      CHANGE THIS FOR ONLY AWS/GCP
   yum:
     name: "{{ docker_container_selinux_url }}"
     state: "{{ docker_package_state }}"

 - name: Install docker
   yum:
     name: "{{ docker_package }}"
     state: "{{ docker_package_state }}"
     enablerepo: "{{ rhel_enabled_repos }}"
   notify: restart docker service
 
 - name: Set docker service to be started and  enabled
   service:
     name: docker
     state: "{{ docker_service_state }}"
     enabled: "{{ docker_service_enabled }}"
 
 - name: FOrce the restart docker service handler to be run
   meta: flush_handlers
 
 - include_tasks: docker-users.yml
   when: docker_users | length > 0

...

