---

# ansible_ssh_common_args: '-o User=ec2-user -o ProxyCommand="nc --proxy 127.0.0.1:3128 %h %p"'

 ENVIRONMENT_HYPHEN: "{{(ENVIRONMENT|default('',true)=='')|ternary('',((ENVIRONMENT|default('',true))+'-'))}}"
 GROUP_NAME:  "proxy"

 yum_packages:
 - vim
 - tree

# rhel_rpms_repo: rhui-REGION-rhel-server-releases
 #rhel_extra_rpms_repo: rhui-REGION-rhel-server-extras

 rhel_extra_rpms_repo: rhui-rhel-7-server-rhui-extras-rpms
 rhel_rpms_repo: rhui-rhel-7-server-rhui-rpms

 rhel_repo_list:
 - "{{ rhel_rpms_repo }}"
 - "{{ rhel_extra_rpms_repo }}"
 
 rhel_enabled_repos: "{{ rhel_repo_list|join(',') }}"

 enabled_repos: "{{ rhel_enabled_repos }}"

 nginx_image_name: nginx:1.18.0
 nginx_container: nginx

...

